# Generated by Django 4.1.2 on 2022-10-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tele2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('act_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Теле2',
                'verbose_name_plural': 'Теле2 данные',
            },
        ),
        migrations.CreateModel(
            name='Tele2File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('act_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Yandex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_id', models.IntegerField(verbose_name='Id в яндекс')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='Номер телефона')),
                ('address_city', models.CharField(max_length=50, null=True, verbose_name='Город')),
                ('address_street', models.CharField(max_length=100, null=True, verbose_name='Улица')),
                ('address_house', models.CharField(max_length=6, null=True, verbose_name='Дом')),
                ('address_office', models.CharField(max_length=100, null=True, verbose_name='Офис')),
                ('act_date', models.DateField(verbose_name='Дата акутальности')),
            ],
            options={
                'verbose_name': 'Яндекс данные',
                'verbose_name_plural': 'Яндекс данные',
            },
        ),
        migrations.CreateModel(
            name='YandexBad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_id', models.IntegerField(null=True, verbose_name='Id в яндекс')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='Номер телефона')),
                ('address_city', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('address_street', models.CharField(max_length=100, null=True, verbose_name='Улица')),
                ('address_house', models.CharField(max_length=6, null=True, verbose_name='Дом')),
                ('address_office', models.CharField(max_length=100, null=True, verbose_name='Офис')),
                ('act_date', models.DateField(verbose_name='Дата акутальности')),
            ],
            options={
                'verbose_name': 'Яндекс не валидные данные',
                'verbose_name_plural': 'Яндекс не валидные данные',
            },
        ),
        migrations.CreateModel(
            name='YandexFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='yandex_files')),
                ('file_type', models.CharField(choices=[('no_address', 'без адресов'), ('with_addresses', 'с адресами')], max_length=14)),
                ('act_date', models.DateField()),
            ],
        ),
    ]
