# Generated by Django 4.1.2 on 2022-10-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandex',
            name='address_house',
            field=models.CharField(max_length=100, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='yandexbad',
            name='address_house',
            field=models.CharField(max_length=100, null=True, verbose_name='Дом'),
        ),
    ]
