# Generated by Django 4.1.2 on 2022-10-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0003_alter_tele2file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pochta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('home_phone', models.CharField(max_length=30, null=True, verbose_name='Домашний телефон')),
                ('arrival_local_dts', models.DateField(verbose_name='Дата получения данных')),
                ('act_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PochtaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pochta_file')),
                ('act_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='tele2file',
            options={'verbose_name': 'Файл с данными теле2', 'verbose_name_plural': 'Файлы с данными теле2'},
        ),
        migrations.AlterModelOptions(
            name='yandexfile',
            options={'verbose_name': 'Файл с данными яндекса', 'verbose_name_plural': 'Файлы с данными яндекса'},
        ),
    ]
