# Generated by Django 4.1.2 on 2022-10-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip', '0004_pochta_pochtafile_alter_tele2file_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pochta',
            options={'verbose_name': 'Данные почты', 'verbose_name_plural': 'Данные почты'},
        ),
        migrations.RemoveField(
            model_name='pochta',
            name='act_date',
        ),
    ]
